[tox]
install_command = uv sync --all-extras
envlist = lint, py{310,311,312,313}

[testenv]
description = Run unit tests
runner = uv-venv-lock-runner
commands = uv run pytest -v --ignore redun/experimental {posargs:redun}

[testenv:lint]
description = Lint all the things
runner = uv-venv-lock-runner
commands = uv run pre-commit run --all-files

[testenv:test-postgres]
description = Run unit tests with Postgres backend
runner = uv-venv-lock-runner
basepython = python3.12
extras = postgres
allowlist_externals = bin/test_postgres.sh
commands = bin/test_postgres.sh
