name: sphinx-docs
on:
  push:
    branches:
      - main

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Get uv version
        id: uv-version
        run: echo "version=$(cat .uv-version)" >> $GITHUB_OUTPUT

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          version: ${{ steps.uv-version.outputs.version }}
          python-version: '3.11'
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked --group docs

      - name: Build sphinx docs
        run: |
          cd docs
          uv run make api html

      - name: Checkout gh-pages branch
        uses: actions/checkout@v5
        with:
          ref: gh-pages
          path: gh-pages

      - name: Commit documentation changes
        run: |
          cp -r docs/build/html/* gh-pages/
          cd gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -am "Update documentation" && git push || true
          # The above command will fail if no changes were present, so we ignore that.
